common_task_template: &COMMON_TASK_TEMPLATE
  env:
    DEPENDENCIES: git ansible podman
    FEDORA_DEP: ansible-collection-ansible-posix
                ansible-collection-ansible-utils
    CIRRUS_WORKING_DIR: /root/ovn-heater
    PHYS_DEPLOYMENT: ${CIRRUS_WORKING_DIR}/physical-deployments/ci.yml

  # Make sure we use all the disk available to us.  Similar to the steps
  # described at:
  # https://cloud.google.com/compute/docs/disks/resize-persistent-disk
  #
  # Use "findmnt -n -o SOURCE /" and parse outputs of the form:
  # /dev/<device><partition-number>
  # OR
  # /dev/<device><partition-number>[text]
  resize_disk_script:
    - d=$(findmnt -n -o SOURCE / | cut -f 1 -d '[' | cut -f 3 -d '/' | grep -oE '[a-zA-Z]+')
    - p=$(findmnt -n -o SOURCE / | cut -f 1 -d '[' | cut -f 3 -d '/' | grep -oE '[0-9]+')
    - t=$(df --output=fstype /root | grep -v Type)
    - growpart /dev/$d $p || true
    - '[ "$t" = "ext4" ] && resize2fs /dev/$d$p || true'
    - '[ "$t" = "xfs" ] && xfs_growfs -d /root || true'
    - '[ "$t" = "btrfs" ] && btrfs filesystem resize max /root || true'

  configure_ssh_script:
    - mkdir -p /root/.ssh/
    - ssh-keygen -t rsa -N '' -q -f /root/.ssh/id_rsa
    - ssh-keyscan $(hostname) >> /root/.ssh/known_hosts
    - cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
    - chmod og-wx /root/.ssh/authorized_keys
    - ssh root@$(hostname) -v echo Hello

  install_dependencies_script:
    - 'if [ $(which dnf) ]; then
        dnf install -y ${DEPENDENCIES} ${FEDORA_DEP};
       fi'
    - 'if [ $(which apt) ]; then
        apt update && apt install -y ${DEPENDENCIES};
       fi'

runtime_builder_task:
  << : *COMMON_TASK_TEMPLATE

  compute_engine_instance:
    matrix:
      - image_project: fedora-cloud
        image: family/fedora-cloud-38
      - image_project: ubuntu-os-cloud
        image: family/ubuntu-2304-amd64
    platform: linux
    memory: 8G
    disk: 40

  runtime_cache:
    folder: runtime-cache
    fingerprint_script:
      - echo ${CIRRUS_BUILD_ID}
      - echo ${CIRRUS_OS}
      - awk -F= '/^ID/{print$2}' /etc/os-release | tr -d '"'

  unpack_caches_script:
    - mkdir -p runtime runtime-cache
    - tar -xzf runtime-cache/runtime.tar.gz || true
    - podman load -i runtime/ovn-fake-multinode/ovn-multi-node-image.tar || true

  install_script:
    - 'sed -i "s/<host>/$(hostname)/g" ${PHYS_DEPLOYMENT}'
    - ./do.sh install

  pack_caches_script:
    - rm -rf runtime-cache/*
    - tar -czf runtime-cache/runtime.tar.gz runtime

  upload_caches:
    - runtime

low_scale_task:
  depends_on:
    - runtime_builder

  << : *COMMON_TASK_TEMPLATE

  compute_engine_instance:
    matrix:
      - image_project: fedora-cloud
        image: family/fedora-cloud-38
      - image_project: ubuntu-os-cloud
        image: family/ubuntu-2304-amd64
    platform: linux
    memory: 8G
    disk: 40

  matrix:
    - name: 'Test Scenario - non IC'
      env:
        TEST_SCENARIO: 'test-scenarios/ovn-low-scale.yml'
        TEST_SCENARIO_OUTDIR: 'low-scale'
    - name: 'Test Scenario - IC'
      env:
        TEST_SCENARIO: 'test-scenarios/ovn-low-scale-ic.yml'
        TEST_SCENARIO_OUTDIR: 'low-scale-ic'

  matrix:
    - name: 'Address Family - dual'
      env:
        IP4: True
        IP6: True
    - name: 'Address Family - ip4'
      env:
        IP4: True
        IP6: False
    - name: 'Address Family - ip6'
      env:
        IP4: False
        IP6: True

  runtime_cache:
    folder: runtime-cache
    fingerprint_script:
      - echo ${CIRRUS_BUILD_ID}
      - echo ${CIRRUS_OS}
      - awk -F= '/^ID/{print$2}' /etc/os-release | tr -d '"'

  unpack_caches_script:
    - tar -xzf runtime-cache/runtime.tar.gz
    - podman load -i runtime/ovn-fake-multinode/ovn-multi-node-image.tar

  test_script:
    - 'sed -i "s/<host>/$(hostname)/g" ${PHYS_DEPLOYMENT}'
    - 'sed -i "s/^  log_cmds\: False/  log_cmds\: True/" ${TEST_SCENARIO}'
    - 'sed -i "s/^  run_ipv4\: .*\$/  run_ipv4\: $IP4/" ${TEST_SCENARIO}'
    - 'sed -i "s/^  run_ipv6\: .*\$/  run_ipv6\: $IP6/" ${TEST_SCENARIO}'
    - ./do.sh install-deps
    - ./do.sh refresh-tester
    - ./do.sh run ${TEST_SCENARIO} ${TEST_SCENARIO_OUTDIR}

  check_logs_script:
    - ./utils/logs-checker.sh

  always:
    test_logs_artifacts:
      path: test_results/**
